repo: "hear-me-oh-content"
canvasCourse: "web-design-2"

inherit:
  - naming-restrict-live
  - git-2
  - html
  - html-good-semantics
  - aria-landmarks

html:
  - path: "index.html"
    hasNot:
      - "img:not([alt])"
      - check: 'img[alt=""]:not([role="presentation"]):not([aria-details])'
        message: 'Is this image an important part of the content? If so it needs a descriptive `alt=""` attribute or the `aria-details` attribute. If it’s only for presentation add the attribute `role="presentation"`'

functionality:
  - path: "index.html"
    label: "Accessibility"
    tests:
      - |
        /** Double check all links have unique inner text or ARIA labels. **/
        const links = $$("a");
        let linkText = []
        let uniqText = false;
        [].forEach.call(links, (elem) => {
          let text = elem.innerText.trim() + (elem.getAttribute("aria-label") || "").trim();
          linkText.push(text.replace(/\s*/, ''));
        });
        uniqText = new Set(linkText);
        if (uniqText.size != linkText.length) {
          fail("Some links have duplicate content without unique labels.")
        }
        pass();
